version: "3.8"

services:
  discovery-service:
    container_name: discovery-service
    hostname: discovery-service
    networks:
      - web-network
    build:
      context: .
    restart: always
    environment:
      DISCOVERY_SERVICE_PORT: 8084
      DISCOVERY_SERVICE_LOGGER_LEVEL: INFO

networks:
  web-network:
    external: true