version: "3.8"

services:
  discovery-service:
    container_name: discovery-service
    hostname: discovery-service
    networks:
      - web-network
    build:
      context: ./app
      target: discovery-service
    restart: always
    ports:
      - "${DISCOVERY_SERVICE_PORT}:${DISCOVERY_SERVICE_PORT}"
    environment:
      DISCOVERY_SERVICE_PORT: ${DISCOVERY_SERVICE_PORT}
      DISCOVERY_SERVICE_LOGGER_LEVEL: ${DISCOVERY_SERVICE_LOGGER_LEVEL}

networks:
  web-network:
    external: true