version: "3.8"

services:
  transfer-service:
    build: .
    ports:
      - "${TRANSFER_SERVICE_PORT}:${TRANSFER_SERVICE_PORT}"
    environment:
      TRANSFER_SERVICE_PORT: ${TRANSFER_SERVICE_PORT}
      TRANSFER_SERVICE_LOGGER_LEVEL: ${TRANSFER_SERVICE_LOGGER_LEVEL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
