version: "3.8"

services:
  transfer-service:
    container_name: transfer-service
    hostname: transfer-service
    networks:
      - web-network
    build:
      context: .
    restart: always
    expose:
      - 8087
    environment:
      TRANSFER_SERVICE_PORT: 8087
      TRANSFER_SERVICE_LOGGER_LEVEL: INFO
      KEYCLOAK_REALM: gravity
      KEYCLOAK_EXTERNAL_URL: http://localhost:8181
      KEYCLOAK_INTERNAL_URL: http://keycloak:8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

networks:
  web-network:
    external: true