version: "3.8"

services:
  accounts-service:
    container_name: accounts-service
    hostname: accounts-service
    networks:
      - web-network
    build:
      context: .
    restart: always
#    expose:
#      - 8083
    ports:
      - "8083:8083"
    environment:
      ACCOUNTS_SERVICE_PORT: 8083
      ACCOUNTS_SERVICE_LOGGER_LEVEL: INFO
      KEYCLOAK_REALM: gravity
      KEYCLOAK_BASE_URL: http://localhost:8181
      KEYCLOAK_CLIENT_ID: accounts-service
      KEYCLOAK_CLIENT_SECRET: bWIHJuPOuGFbHcsTV8gFYDtIFnlhGrNe
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

networks:
  web-network:
    external: true
