version: "3.8"

services:
  accounts-service:
    build: .
    ports:
      - "${ACCOUNTS_SERVICE_PORT}:${ACCOUNTS_SERVICE_PORT}"
    environment:
      ACCOUNTS_SERVICE_PORT: ${ACCOUNTS_SERVICE_PORT}
      ACCOUNTS_SERVICE_LOGGER_LEVEL: ${ACCOUNTS_SERVICE_LOGGER_LEVEL}
      ACCOUNTS_SERVICE_KEYCLOAK_REALM: ${ACCOUNTS_SERVICE_KEYCLOAK_REALM}
      ACCOUNTS_SERVICE_KEYCLOAK_BASE_URL: ${ACCOUNTS_SERVICE_KEYCLOAK_BASE_URL}
