spring:
  application:
    name: gateway-service
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        instance-id: "${spring.application.name}:${server.port}:${random.value}"
        health-check-path: /actuator/health
        health-check-interval: 5s
    gateway:
      server:
        webflux:
          routes:
            - id: accounts-service
              uri: lb://accounts-service
              predicates:
                - Path=/api/v1/accounts/**
            - id: cash-service
              uri: lb://cash-service
              predicates:
                - Path=/api/v1/cash/**
            - id: transfer-service
              uri: lb://transfer-service
              predicates:
                - Path=/api/v1/transfer/**
          discovery:
            locator:
              enabled: true # Автоматическое создание маршрутов на основе сервисов, зарегистрированных в реестре
              lower-case-service-id: true # Приводит имя сервиса в URL к нижнему регистру
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
      client:
        provider:
          keycloak:
            issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

server:
  port: ${GATEWAY_SERVICE_PORT}

logging:
  level:
    org.springframework: ${GATEWAY_SERVICE_LOGGER_LEVEL}

app:
  keycloak:
    realm: ${KEYCLOAK_REALM}
    serverUrl: ${KEYCLOAK_BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info