version: "3.8"

services:
  keycloak-service:
    build: .
    ports:
      - "${KEYCLOAK_SERVICE_PORT}:${KEYCLOAK_SERVICE_PORT}"
    environment:
      KEYCLOAK_SERVICE_PORT: ${KEYCLOAK_SERVICE_PORT}
      KEYCLOAK_SERVICE_LOGGER_LEVEL: ${KEYCLOAK_SERVICE_LOGGER_LEVEL}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM_RS256_PUBLIC_KEY: ${KEYCLOAK_REALM_RS256_PUBLIC_KEY}
      KEYCLOAK_DEFAULT_USER_GROUP: ${KEYCLOAK_DEFAULT_USER_GROUP}
      KEYCLOAK_DEFAULT_USER_ROLE: ${KEYCLOAK_DEFAULT_USER_ROLE}
      KEYCLOAK_DEFAULT_USER_ROLE_TYPE: ${KEYCLOAK_DEFAULT_USER_ROLE_TYPE}