version: "3.8"

services:
  cash-service:
    build: .
    ports:
      - "${CASH_SERVICE_PORT}:${CASH_SERVICE_PORT}"
    environment:
      CASH_SERVICE_PORT: ${CASH_SERVICE_PORT}
      CASH_SERVICE_LOGGER_LEVEL: ${CASH_SERVICE_LOGGER_LEVEL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
