version: "3.8"

services:
  notification-service:
    build: .
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    environment:
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}
      NOTIFICATION_SERVICE_LOGGER_LEVEL: ${NOTIFICATION_SERVICE_LOGGER_LEVEL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
