version: "3.8"

services:
  gateway-service:
    build: .
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    environment:
      GATEWAY_SERVICE_PORT: ${GATEWAY_SERVICE_PORT}
      GATEWAY_SERVICE_LOGGER_LEVEL: ${GATEWAY_SERVICE_LOGGER_LEVEL}
      GATEWAY_SERVICE_KEYCLOAK_REALM: ${GATEWAY_SERVICE_KEYCLOAK_REALM}
      GATEWAY_SERVICE_KEYCLOAK_BASE_URL: ${GATEWAY_SERVICE_KEYCLOAK_BASE_URL}
